// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhzflrudggwugpvrtumm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoemZscnVkZ2d3dWdwdnJ0dW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM4NTMsImV4cCI6MjA3Mzg2OTg1M30.uCU2YwxJAcKVDhQD7Wf6wszZqpkKprOkvfEssYrL6N0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});